name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Ensure your project is actually using .NET 8

      - name: Restore dependencies
        run: dotnet restore CompleteMethodAdd.sln

      - name: Build project
        run: dotnet build CompleteMethodAdd.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test CompleteMethodAdd.sln --no-build --configuration Release --verbosity normal
        
      - name: Check Protected Files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)

          echo "🔍 The following files were changed:"
          echo "$CHANGED_FILES"

          PROTECTED_FILES=".github/workflows/classroom.yml"

          for file in $PROTECTED_FILES; do
            if echo "$CHANGED_FILES" | grep -Fxq "$file"; then
              echo "❌ Error: Protected file $file has been modified!"
              exit 1
            fi
          done
